[tool.poetry]
name = "mms-magnetotail-survey"
version = "0.1.0"
description = ""
authors = ["Tien Vo <tien.a.vo@proton.me>"]
readme = "README.md"
packages = [{include = "lib", from="src"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pyspedas = "^1.4.40"
tvolib = "*"
h5py = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
